### ISSUE TITLE
Coverage combine is additive.

### ISSUE THREAD

**Issue by Lukasa** [nedbat/coveragepy#11]
Discussed at PyCon 2016.

When running `coverage combine`, coverage will merge the information not only from every generated covfile, but also from the `.coverage` result file from the previous run of `coverage combine` if that file is still in the directory.

That can lead to misleading coverage results where lines are reported as covered because they *were* covered at some time in the past, even if they aren't now.

**Comment by nedbat** [comment]
I agree this is misleading.  The idea originally was that combine could be used to fold in new data.  I could add `--append` switch to mirror the same considerations in `coverage run`.  This would be a compatibility change, but I think a good one.

**Comment by nedbat** [comment]
Changed in https://bitbucket.org/ned/coveragepy/commits/f4e4c627a486a3d2eeb56809d8886c179108d1fe
Now the default is to ignore an existing .coverage file, and `--append` gets you the old behavior.
