### ISSUE TITLE
Disable install of versioned entrypoints

### ISSUE THREAD

**Issue by jakirkham** [nedbat/coveragepy#13]
Is there or can there be an option to disable installation of the Python versioned entrypoints (e.g. `coverage3` and `coverage-3.5`)? Thanks.

cc @ericmjl

**Comment by nedbat** [comment]
There's isn't such an option.  Can you tell me about why you don't want to install them?

**Comment by jakirkham** [comment]
We use `coverage` in [`conda`]( http://conda.pydata.org/docs/ ). So, in any environment `coverage` is installed, there is only one Python and so there is only one version present. As a result, it has been argued it is a bit silly to have versioned entrypoints.

**Comment by nedbat** [comment]
I guess it isn't necessary to have the versioned names, but I'm not hearing a problem.

**Comment by jakirkham** [comment]
It's true there isn't a problem per se. This is more of a user request/feature type question.
