### ISSUE TITLE
Broken build with python 3.2 (https://travis-ci.org)

### ISSUE THREAD

**Issue by Goblenus** [nedbat/coveragepy#15]
I'm trying to build [my python app](https://github.com/Goblenus/WallhavenApi) with python 3.2, using [Travis CI](https://travis-ci.org), but it failed with error "SyntaxError: invalid syntax" at "coverage/annotate.py".

[Build log](http://pasted.co/42951096)

Thank you.

**Comment by Goblenus** [comment]
Oh, sorry python 3.2 is not supported. But is there any solution for 3.2?

**Comment by nedbat** [comment]
You could use an older version of coverage.py (3.7.1 supported Python 3.2).  But are you sure you need to support 3.2? It's old, and there hadn't been much adoption of Python 3 when it came out.  These days, libraries aren't supporting it.

**Comment by Goblenus** [comment]
Some people continue to use python 3.2, and I'd like to build my app with 3.2 to fit their needs.
