### ISSUE TITLE
Reinitializing Coverage.data during measurement renders report unusable

### ISSUE THREAD

**Issue by gergelypolonkai** [nedbat/coveragepy#25]
I’m trying to do something esoteric: I have a `unittest` test runner that initializes a `Coverage` object at start, then saves `cov.data` after each test and reinitializes `cov.data` with a new `CoverageData` instance, so the next test starts with an empty one. At the end of the test run I combine all the data objects, and assign it back to `cov.data`. However, when I run `cov.report()`, it fails, statisg it has nothing to report.

**Comment by gergelypolonkai** [comment]
In the evening (CET timezone) I can provide minimal code and traceback info, too.

**Comment by gergelypolonkai** [comment]
Here is the result class I use. I tried to clean it up as much as I could (my experiment has a lot of other stuff in it), I hope I didn’t left anything important out. Just let me know if you need some clarification.

```python
class CoverageResult(unittest.result.TestResult):
    def __init__(self,
                 stream, destriptions, verbosity,
                 coverage_sources=None, **kwargs):
        self.verbosity = verbosity

        if coverage_sources:
            self.coverage = coverage.coverage(branch=True, include=coverage_sources)
        else:
            self.coverage = None

        self.test_data = {}

    def startTest(self, test):
        self.test_data[test] = {}

        if self.coverage:
            self.coverage.start()

        super(CoverageResult, self).startTest(test)

    def stopTest(self, test):
        super(CoverageResult, self).stopTest(test)

        if self.coverage:
            self.coverage.stop()
            self.test_data[test]['coverage'] = self.coverage.data
            self.coverage.data = coverage.CoverageData()

            if self.verbosity > 2:
                self.coverage.report()

            self.coverage.erase()

        # This is needed so I don’t erase the result I just saved
        self.coverage.erase()

    @property
    def coverage_data(self):
        for test, data in self.test_data:
            self.coverage.data.update(d['coverage'])

        return self.coverage
```

**Comment by nedbat** [comment]
Without a runnable example, it's hard to know what's going wrong.  Maybe the best thing would be to stick with the documented API, and start a new coverage instance for each test, instead of swapping out data objects?

**Comment by gergelypolonkai** [comment]
I made one, and it is working. After my initial surprise and comparing the two pieces of code it turned out the bug(?) is gone with 4.3. My old experiment was using 4.2.

Sorry for the noise.
