### ISSUE TITLE
coverage-4.4-cp27-cp27mu-manylinux1_x86_64.whl is missing the CTracer

### ISSUE THREAD

**Issue by renstrom** [nedbat/coveragepy#30]
```
$ ./env/bin/pip install -I coverage
Collecting coverage
  Downloading http://<mirror>/packages/coverage/download/17281/coverage-4.4-cp27-cp27mu-manylinux1_x86_64.whl (193kB)
    100% |████████████████████████████████| 194kB 5.0MB/s
Installing collected packages: coverage
Successfully installed coverage-4.4
$ ./env/bin/py.test --junitxml=junitxml-result.xml --cov-report=html --cov-report=xml --cov-report=term --cov=agent agent
Traceback (most recent call last):
  ...
coverage.misc.CoverageException: Can't support concurrency=gevent with PyTracer, only threads are supported
make: *** [coverage] Error 1
```

However by re-installing coverage using `--no-binary=coverage` the CTracer works fine.

    $ ./env/bin/pip install -I --no-binary=coverage coverage

**Comment by nedbat** [comment]
Hmm, did the wheel not include the compiled CTracer?  Can you install the wheel again and show the output of "coverage debug sys"?

**Comment by nedbat** [comment]
Ugh, I see it myself:
```
undefined symbol: PyUnicodeUCS2_FromFormat
```

**Comment by nedbat** [comment]
I've removed the bad wheel file from PyPI.  Not sure what went wrong there, but I'll look into it.

**Comment by nedbat** [comment]
Looks like the "mu" wheels reused the tracer.so from the "m" wheels. I've deleted the four "mu" wheels from PyPI.

**Comment by renstrom** [comment]
Thanks for the quick fix!
